obj-y += libservice_version.o
obj-y += btsrv_main.o
obj-y += btsrv_config.o
obj-y += core/
obj-y += profile/
obj-y += btif/

ccflags-y += -I${ZEPHYR_BASE}/ext/actions/private/libbt_service/include
ccflags-y += -I${ZEPHYR_BASE}/subsys/bluetooth
ccflags-y += -I${ZEPHYR_BASE}/subsys/bluetooth/controller/include
ccflags-y += -I${ZEPHYR_BASE}/subsys/btstack

