obj-y += btif_base.o
obj-y += btif_a2dp.o
obj-y += btif_avrcp.o
obj-y += btif_hfp.o
obj-y += btif_hfp_ag.o
obj-y += btif_tws.o
obj-y += btif_spp.o
obj-y += btif_pbap.o
obj-y += btif_map.o
obj-y += btif_hid.o
obj-y += btif_pts_test.o

ccflags-y += -I${ZEPHYR_BASE}/ext/actions/private/libbt_service/include